### ISSUE TITLE
Supporting apple cert root file path in function param gives more flexibity in program.

### ISSUE THREAD

**Issue by jawad-khan** [rickwierenga/app-store-notifications-v2-validator#1]
Supporting apple cert root file path in function param gives more flexibity in program.
Also can we upgrade  cryptography to 40.0.2 and PyJWT to 2.7.0.

**Comment by rickwierenga** [comment]
Thanks for the suggestions! Do you want to open a PR?

**Comment by jawad-khan** [comment]
Yes, I would love to.

**Comment by jawad-khan** [comment]
Should I create a pull request from fork? since I don't have permission to push a branch.

**Comment by rickwierenga** [comment]
Yes

**Comment by jawad-khan** [comment]
Done.
