### ISSUE TITLE
Issue in cert file path reading

### ISSUE THREAD

**Issue by jawad-khan** [rickwierenga/app-store-notifications-v2-validator#4]
Code is not picking apple root cert file path from param or default path if environment var is not None.

**Comment by jawad-khan** [comment]
Create PR against this issue.
https://github.com/rickwierenga/app-store-notifications-v2-validator/pull/3

**Comment by rickwierenga** [comment]
Merged, thanks!

**Comment by jawad-khan** [comment]
Can you please update the PyPI version?

**Comment by jawad-khan** [comment]
@rickwierenga Any update on PyPI version?

**Comment by rickwierenga** [comment]
Did that yesterday, forgot to respond here :)

**Comment by jawad-khan** [comment]
Well its not working for me atleast.
pip install app-store-notifications-v2-validator==0.0.7
<img width="1071" alt="Screenshot 2023-06-08 at 2 14 43 PM" src="https://github.com/rickwierenga/app-store-notifications-v2-validator/assets/5320368/dcfe6f6b-779b-48d9-999d-72aea8b51345">

**Comment by jawad-khan** [comment]
Also

![Uploading Screenshot 2023-06-08 at 3.02.12 PM.png…]()

**Comment by jawad-khan** [comment]
Also

<img width="1298" alt="Screenshot 2023-06-08 at 3 03 06 PM" src="https://github.com/rickwierenga/app-store-notifications-v2-validator/assets/5320368/9e264fe5-852e-4caf-90c5-46ef260a128c">

**Comment by rickwierenga** [comment]
Oops, something must have gone wrong. Can you confirm it's working now?

**Comment by jawad-khan** [comment]
yup its working now. Thanks.
