### ISSUE TITLE
Error due to insufficient _decode_jws() argument in parse() of subscription renewal notification

### ISSUE THREAD

**Issue by leftom** [rickwierenga/app-store-notifications-v2-validator#5]
Issue Description:
When calling the parse() method on a subscription renewal notification, an error occurs because _decode_jws() has received only one required argument.

Error Log:
```
File "/usr/local/lib/python3.10/site-packages/app_store_notifications_v2_validator/__init__.py", line 78, in parse
    signedRenewalInfo = _decode_jws(payload["data"]["signedRenewalInfo"])
TypeError: _decode_jws() missing 1 required positional argument: 'root_cert_path'"
```

Problem Cause:
This error may be caused by the fact that _decode_jws() requires two arguments (token and root_cert_path), but only one argument is passed in the parse() method for processing when signedRenewalInfo is included.
https://github.com/rickwierenga/app-store-notifications-v2-validator/blob/ce0362521ebeb6cedfa049d847fd8dbfb862dcde/app_store_notifications_v2_validator/__init__.py#L78

As a suggested fix, I suggest passing the second argument root_cert_path to _decode_jws() appropriately.

I've been using this software and find it incredibly helpful due to its simplicity and convenience. I'm truly grateful for your work. Thank you so much.

**Comment by rickwierenga** [comment]
Hi, thanks for reporting this and the kind words.

Could you confirm that https://github.com/rickwierenga/app-store-notifications-v2-validator/commit/2bbdf7d98e8fe9125fa1f952855de06ea6df9368 fixes it? Then I will update the version on PyPI.

**Comment by leftom** [comment]
Thank you. I'll check it works.

**Comment by leftom** [comment]
Thank you for fix the bug. I am happy to report that I have tested the fix and it now works as expected. 
I really appreciate your quick response and effective solution.

**Comment by adorum** [comment]
Hi @rickwierenga can you please publish a new PyPI version with the fix? Thanks

**Comment by rickwierenga** [comment]
done
