### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by schunlee** [rickwierenga/app-store-notifications-v2-validator#6]
I suggest to comment #25 `fn = os.path.expanduser(fn)`
because sounds like force me to put apple cert in home dir, perhaps put full file path is good. Just a suggestion.
btw, the tool is so cool.

**Comment by rickwierenga** [comment]
Thanks!

Keeping this allows the expansion of the home directory, but does not require it. From the docs:

> if the path does not begin with a tilde, the path is returned unchanged.

https://docs.python.org/3/library/os.path.html
